### ISSUE TITLE
Please provide a version that doesn't rely on PackageKit

### ISSUE THREAD

**Issue by pavelbraginskiy** [LaurentTreguier/Discord-installer#1]
For reasons unknown, PackageKit prevents dnf from working properly for me, and I know others who have similar issues. For this reason, I don't wish to have PackageKit installed.

**Comment by LaurentTreguier** [comment]
Does this happen randomly ? Or is it happening on specific systems only ?

**Comment by pavelbraginskiy** [comment]
I think it's only on certain systems. It's an issue with package kit, though.

**Comment by LaurentTreguier** [comment]
I rolled back to using yum/dnf directly, so version 1.4.0 isn't going to require PackageKit. Tell me if you still have any problem !

**Comment by pavelbraginskiy** [comment]
Thank you very much!

**Comment by pavelbraginskiy** [comment]
Actually, it seems that the package at [tcg/discord](https://copr.fedorainfracloud.org/coprs/tcg/discord/) still has PackageKit as a dependency.

```
$ rpm -qR Discord-installer
/bin/bash
/bin/sh
/bin/sh
PackageKit
coreutils
curl
dos2unix
libnotify
polkit
rpm-build
rpmdevtools
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
systemd
```
